<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="G-0439" name="validateCollege_InformationSRM.ValidateUpdatedCollege_Information" tests="6" failures="0" timestamp="4 May 2016 09:31:58 GMT" time="0.005" errors="6">
  <testcase name="SRM__Lead_Details" time="0.000" classname="validateCollege_InformationSRM.ValidateUpdatedCollege_Information">
    <error type="java.lang.Throwable" message="Method ValidateUpdatedCollege_Information.SRM__Lead_Details(java.lang.reflect.Method)[pri:0, instance:validateCollege_InformationSRM.ValidateUpdatedCollege_Information@1025f9f] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method ValidateUpdatedCollege_Information.SRM__Lead_Details(java.lang.reflect.Method)[pri:0, instance:validateCollege_InformationSRM.ValidateUpdatedCollege_Information@1025f9f] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1052)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- SRM__Lead_Details -->
  <testcase name="VerifyLeadInSRM" time="0.000" classname="validateCollege_InformationSRM.ValidateUpdatedCollege_Information">
    <error type="java.lang.Throwable" message="Method ValidateUpdatedCollege_Information.VerifyLeadInSRM(java.lang.reflect.Method)[pri:0, instance:validateCollege_InformationSRM.ValidateUpdatedCollege_Information@1025f9f] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method ValidateUpdatedCollege_Information.VerifyLeadInSRM(java.lang.reflect.Method)[pri:0, instance:validateCollege_InformationSRM.ValidateUpdatedCollege_Information@1025f9f] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1052)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- VerifyLeadInSRM -->
  <testcase name="VerifyNewOpportunityInSRM" time="0.000" classname="validateCollege_InformationSRM.ValidateUpdatedCollege_Information">
    <error type="java.lang.Throwable" message="Method ValidateUpdatedCollege_Information.VerifyNewOpportunityInSRM(java.lang.reflect.Method)[pri:0, instance:validateCollege_InformationSRM.ValidateUpdatedCollege_Information@1025f9f] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method ValidateUpdatedCollege_Information.VerifyNewOpportunityInSRM(java.lang.reflect.Method)[pri:0, instance:validateCollege_InformationSRM.ValidateUpdatedCollege_Information@1025f9f] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1052)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- VerifyNewOpportunityInSRM -->
  <testcase name="BrowseToAddInfoCallLeadPage" time="0.005" classname="validateCollege_InformationSRM.ValidateUpdatedCollege_Information">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at validateCollege_InformationSRM.ValidateUpdatedCollege_Information.BeforeNavigation(ValidateUpdatedCollege_Information.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- BrowseToAddInfoCallLeadPage -->
  <testcase name="VerifyOpportunityInSRM" time="0.000" classname="validateCollege_InformationSRM.ValidateUpdatedCollege_Information">
    <error type="java.lang.Throwable" message="Method ValidateUpdatedCollege_Information.VerifyOpportunityInSRM(java.lang.reflect.Method)[pri:0, instance:validateCollege_InformationSRM.ValidateUpdatedCollege_Information@1025f9f] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method ValidateUpdatedCollege_Information.VerifyOpportunityInSRM(java.lang.reflect.Method)[pri:0, instance:validateCollege_InformationSRM.ValidateUpdatedCollege_Information@1025f9f] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1052)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- VerifyOpportunityInSRM -->
  <testcase name="Lead_Flow" time="0.000" classname="validateCollege_InformationSRM.ValidateUpdatedCollege_Information">
    <error type="java.lang.Throwable" message="Method ValidateUpdatedCollege_Information.Lead_Flow(java.lang.reflect.Method)[pri:0, instance:validateCollege_InformationSRM.ValidateUpdatedCollege_Information@1025f9f] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method ValidateUpdatedCollege_Information.Lead_Flow(java.lang.reflect.Method)[pri:0, instance:validateCollege_InformationSRM.ValidateUpdatedCollege_Information@1025f9f] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1052)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- Lead_Flow -->
</testsuite> <!-- validateCollege_InformationSRM.ValidateUpdatedCollege_Information -->
